# Generated by Django 5.1.1 on 2025-05-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phones', 'Phones'), ('Computers', 'Computers'), ('Smart Watch', 'Smart Watch'), ('Camera', 'Camera'), ('HeadPhones', 'HeadPhones'), ('Gaming', 'Gaming'), ("Women's Fashion", "Women's Fashion"), ("Men's Fashion", "Men's Fashion"), ('Electronics', 'Electronics'), ('Home & Lifestyles', 'Home & Lifestyles'), ('Medicine', 'Medicine'), ('Sports & Outdoor', 'Sports & Outdoor'), ('Toys', 'Toys'), ('Groceries & Pets', 'Groceries & Pets'), ('Health & Beauty', 'Health & Beauty')], default='Electronics', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='wish_list',
            field=models.BooleanField(default=False),
        ),
    ]
